### ISSUE TITLE
ev2460

### ISSUE THREAD

**Issue by ostway** [markbolhuis/openeizo#1]
Hi. thanks for release! 
I tested it quickly on my ev2460 and brightness value showed normal, but setter no work
![image](https://user-images.githubusercontent.com/19193934/114480391-2983aa00-9c0b-11eb-8b51-9efd9f920f61.png)

I'll try a little bit later sniff packets via Wireshar and upload

**Comment by markbolhuis** [comment]
Thank you.
Interesting that reading would return the correct value but not writing. I'm not sure what would cause that since the structure is the same.

It would be helpful to have the packets, especially those captured during startup. If you could have wireshark running and capture the traffic exchanged when you start the screen in-style software that would be very helpful.

**Comment by ostway** [comment]
Hello! Sorry, that was my fault. I said, I tested  quickly!

Now I spent a little more time for test it and have good news:
_Brightness_ setter had no effect because option _Auto EcoView_ was enabled. I disable it and setter work fine. And i tested **power**, **gamma**, and **profiles** and work too correct! 
Big thanks frined, good job!
PS: I created branch _ev2460tested_ in my fork and added what i tested.
